FROM golang:1.19.4 AS builder

ENV GOOS=linux
ENV CGO_DISABLED=0

RUN useradd -u 10001 scratchuser

WORKDIR /freebird

COPY go.mod go.sum ./
COPY app app
COPY db db

RUN env GOOS=linux go build -o=/go/bin ./app/cmd/...

RUN ls /go/bin
