// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package data

import (
	"time"
)

type Bird struct {
	ID         int32
	Name       string
	EntityType int32
	BirdFk     int32
	Score      float64
	NPositive  int32
	NNegative  int32
	ImgUrl     string
}

type Tweet struct {
	ID             int32
	Body           string
	BirdFk         int32
	AuthorName     string
	AuthorUsername string
	PostTime       time.Time
	Score          float64
}
