// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package data

import (
	"database/sql"
)

type Bird struct {
	ID         int32
	Name       sql.NullString
	EntityType sql.NullInt32
	BirdFk     sql.NullInt32
	Score      sql.NullFloat64
	NPositive  sql.NullInt32
	NNegative  sql.NullInt32
	ImgUrl     sql.NullString
}

type Tweet struct {
	Body           sql.NullString
	BirdFk         sql.NullInt32
	AuthorName     sql.NullString
	AuthorUsername sql.NullString
	PostTime       interface{}
	Score          sql.NullFloat64
	Certainty      sql.NullFloat64
}
