// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: queries.sql

package data

import (
	"context"
	"database/sql"
)

const getBirds = `-- name: GetBirds :many
SELECT id, name, entity_type, bird_fk, score, n_positive, n_negative, img_url FROM birds ORDER BY score
`

func (q *Queries) GetBirds(ctx context.Context) ([]*Bird, error) {
	rows, err := q.db.QueryContext(ctx, getBirds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Bird
	for rows.Next() {
		var i Bird
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EntityType,
			&i.BirdFk,
			&i.Score,
			&i.NPositive,
			&i.NNegative,
			&i.ImgUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTweets = `-- name: GetTweets :many
SELECT body, bird_fk, author_name, author_username, post_time, score, certainty FROM tweets WHERE bird_fk = $1
`

func (q *Queries) GetTweets(ctx context.Context, birdFk sql.NullInt32) ([]*Tweet, error) {
	rows, err := q.db.QueryContext(ctx, getTweets, birdFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Tweet
	for rows.Next() {
		var i Tweet
		if err := rows.Scan(
			&i.Body,
			&i.BirdFk,
			&i.AuthorName,
			&i.AuthorUsername,
			&i.PostTime,
			&i.Score,
			&i.Certainty,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
