// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: app/api/proto/data.proto

package freebird

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FreebirdEntity int32

const (
	FreebirdEntity_SHILL   FreebirdEntity = 0
	FreebirdEntity_COMPANY FreebirdEntity = 1
)

// Enum value maps for FreebirdEntity.
var (
	FreebirdEntity_name = map[int32]string{
		0: "SHILL",
		1: "COMPANY",
	}
	FreebirdEntity_value = map[string]int32{
		"SHILL":   0,
		"COMPANY": 1,
	}
)

func (x FreebirdEntity) Enum() *FreebirdEntity {
	p := new(FreebirdEntity)
	*p = x
	return p
}

func (x FreebirdEntity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FreebirdEntity) Descriptor() protoreflect.EnumDescriptor {
	return file_app_api_proto_data_proto_enumTypes[0].Descriptor()
}

func (FreebirdEntity) Type() protoreflect.EnumType {
	return &file_app_api_proto_data_proto_enumTypes[0]
}

func (x FreebirdEntity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FreebirdEntity.Descriptor instead.
func (FreebirdEntity) EnumDescriptor() ([]byte, []int) {
	return file_app_api_proto_data_proto_rawDescGZIP(), []int{0}
}

type TweetStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TweetStreamRequest) Reset() {
	*x = TweetStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_proto_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TweetStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TweetStreamRequest) ProtoMessage() {}

func (x *TweetStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TweetStreamRequest.ProtoReflect.Descriptor instead.
func (*TweetStreamRequest) Descriptor() ([]byte, []int) {
	return file_app_api_proto_data_proto_rawDescGZIP(), []int{0}
}

type TweetStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityName      string         `protobuf:"bytes,1,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	EntitySentiment float32        `protobuf:"fixed32,2,opt,name=entity_sentiment,json=entitySentiment,proto3" json:"entity_sentiment,omitempty"`
	EntityImage     string         `protobuf:"bytes,3,opt,name=entity_image,json=entityImage,proto3" json:"entity_image,omitempty"`
	EntityType      FreebirdEntity `protobuf:"varint,4,opt,name=entity_type,json=entityType,proto3,enum=data.FreebirdEntity" json:"entity_type,omitempty"`
}

func (x *TweetStreamResponse) Reset() {
	*x = TweetStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_proto_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TweetStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TweetStreamResponse) ProtoMessage() {}

func (x *TweetStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TweetStreamResponse.ProtoReflect.Descriptor instead.
func (*TweetStreamResponse) Descriptor() ([]byte, []int) {
	return file_app_api_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *TweetStreamResponse) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *TweetStreamResponse) GetEntitySentiment() float32 {
	if x != nil {
		return x.EntitySentiment
	}
	return 0
}

func (x *TweetStreamResponse) GetEntityImage() string {
	if x != nil {
		return x.EntityImage
	}
	return ""
}

func (x *TweetStreamResponse) GetEntityType() FreebirdEntity {
	if x != nil {
		return x.EntityType
	}
	return FreebirdEntity_SHILL
}

type EntityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityType FreebirdEntity `protobuf:"varint,1,opt,name=entity_type,json=entityType,proto3,enum=data.FreebirdEntity" json:"entity_type,omitempty"`
	EntityName string         `protobuf:"bytes,2,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
}

func (x *EntityRequest) Reset() {
	*x = EntityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_proto_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRequest) ProtoMessage() {}

func (x *EntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRequest.ProtoReflect.Descriptor instead.
func (*EntityRequest) Descriptor() ([]byte, []int) {
	return file_app_api_proto_data_proto_rawDescGZIP(), []int{2}
}

func (x *EntityRequest) GetEntityType() FreebirdEntity {
	if x != nil {
		return x.EntityType
	}
	return FreebirdEntity_SHILL
}

func (x *EntityRequest) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

type EntityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gaming string `protobuf:"bytes,1,opt,name=gaming,proto3" json:"gaming,omitempty"`
}

func (x *EntityResponse) Reset() {
	*x = EntityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_proto_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityResponse) ProtoMessage() {}

func (x *EntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_proto_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityResponse.ProtoReflect.Descriptor instead.
func (*EntityResponse) Descriptor() ([]byte, []int) {
	return file_app_api_proto_data_proto_rawDescGZIP(), []int{3}
}

func (x *EntityResponse) GetGaming() string {
	if x != nil {
		return x.Gaming
	}
	return ""
}

var File_app_api_proto_data_proto protoreflect.FileDescriptor

var file_app_api_proto_data_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x14, 0x0a, 0x12, 0x54, 0x77, 0x65, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xbb, 0x01, 0x0a, 0x13, 0x54, 0x77, 0x65, 0x65, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x29, 0x0a, 0x10, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x65, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x53, 0x65, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a,
	0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x46, 0x72, 0x65, 0x65, 0x62, 0x69,
	0x72, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x67, 0x0a, 0x0d, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x46, 0x72, 0x65, 0x65, 0x62, 0x69, 0x72, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x28, 0x0a,
	0x0e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2a, 0x28, 0x0a, 0x0e, 0x46, 0x72, 0x65, 0x65, 0x62,
	0x69, 0x72, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x48, 0x49,
	0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4d, 0x50, 0x41, 0x4e, 0x59, 0x10,
	0x01, 0x32, 0x89, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x46, 0x0a, 0x0b, 0x54, 0x77,
	0x65, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x18, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x77, 0x65, 0x65, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x39, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x13, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a,
	0x10, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x72, 0x65, 0x65, 0x62, 0x69, 0x72,
	0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_api_proto_data_proto_rawDescOnce sync.Once
	file_app_api_proto_data_proto_rawDescData = file_app_api_proto_data_proto_rawDesc
)

func file_app_api_proto_data_proto_rawDescGZIP() []byte {
	file_app_api_proto_data_proto_rawDescOnce.Do(func() {
		file_app_api_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_api_proto_data_proto_rawDescData)
	})
	return file_app_api_proto_data_proto_rawDescData
}

var file_app_api_proto_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_api_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_app_api_proto_data_proto_goTypes = []interface{}{
	(FreebirdEntity)(0),         // 0: data.FreebirdEntity
	(*TweetStreamRequest)(nil),  // 1: data.TweetStreamRequest
	(*TweetStreamResponse)(nil), // 2: data.TweetStreamResponse
	(*EntityRequest)(nil),       // 3: data.EntityRequest
	(*EntityResponse)(nil),      // 4: data.EntityResponse
}
var file_app_api_proto_data_proto_depIdxs = []int32{
	0, // 0: data.TweetStreamResponse.entity_type:type_name -> data.FreebirdEntity
	0, // 1: data.EntityRequest.entity_type:type_name -> data.FreebirdEntity
	1, // 2: data.Data.TweetStream:input_type -> data.TweetStreamRequest
	3, // 3: data.Data.EntityData:input_type -> data.EntityRequest
	2, // 4: data.Data.TweetStream:output_type -> data.TweetStreamResponse
	4, // 5: data.Data.EntityData:output_type -> data.EntityResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_api_proto_data_proto_init() }
func file_app_api_proto_data_proto_init() {
	if File_app_api_proto_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_api_proto_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TweetStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_proto_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TweetStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_proto_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_proto_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_api_proto_data_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_api_proto_data_proto_goTypes,
		DependencyIndexes: file_app_api_proto_data_proto_depIdxs,
		EnumInfos:         file_app_api_proto_data_proto_enumTypes,
		MessageInfos:      file_app_api_proto_data_proto_msgTypes,
	}.Build()
	File_app_api_proto_data_proto = out.File
	file_app_api_proto_data_proto_rawDesc = nil
	file_app_api_proto_data_proto_goTypes = nil
	file_app_api_proto_data_proto_depIdxs = nil
}
